### ISSUE TITLE
gqlgen.yml ==> exec have to be fixed

### ISSUE THREAD

**Issue by fasibio** [fasibio/autogql#3]
```yml
exec:
  filename: graph/generated/generated.go
  package: generated
```

if not there will be syntax error at autogql.resolvers.go
so inside generate_code_resolver.go.tpl generated.Add, generated.Delete ... 
generated have to be more felixible and have to be read from gqlgen.yml config
